addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
install: make get-deps
language: cpp
compiler: gcc
script:
- cd build/release/src
- make -j8